const namespace = 'soniclean/stores';
export const FETCH_STORES = `${namespace}/fetchStores`;
export const SUCCESS_SAVE_STORES = `${namespace}/successsaveStores`;
export const FAILURE_SAVE_STORES = `${namespace}/failuresaveStores`;
export const FAILURE_FETCH_STORES = `${namespace}/failurefetchStores`;
export const GETSTORES = `${namespace}/getstores`;
export const DELETESTORE = `${namespace}/deletestore`;
export const ADDSTORE = `${namespace}/addstore`;
export const UPDATESTORE = `${namespace}/updatestore`;
